// ===== STUDENT DATA =====
const students = [
    {
        id: 1,
        name: "Maria Santos",
        nickname: "Mari",
        gender: "girl",
        section: "A",
        bio: "Future engineer, loves robotics. Case study: Mars Rover prototype.",
        skills: ["Python", "Arduino"],
        hobbies: ["Swimming", "Chess"],
        favSubject: "Physics",
        dreamCareer: "Aerospace Engineer",
        social: "@mari_s",
        certificates: ["Robotics 101"],
        projects: ["Mars Rover"]
    },
    {
        id: 2,
        name: "Juan Dela Cruz",
        nickname: "JC",
        gender: "boy",
        section: "A",
        bio: "Math enthusiast and gamer. Case study: AI Predictor.",
        skills: ["Java", "Math"],
        hobbies: ["Basketball", "Gaming"],
        favSubject: "Math",
        dreamCareer: "Data Scientist",
        social: "@juanDC",
        certificates: ["Math Olympiad"],
        projects: ["AI Predictor"]
    },
    {
        id: 3,
        name: "Elena Gomez",
        nickname: "Ella",
        gender: "girl",
        section: "B",
        bio: "Creative writer and debater. Case study: School Magazine redesign.",
        skills: ["Writing", "Public Speaking"],
        hobbies: ["Reading", "Debate"],
        favSubject: "English",
        dreamCareer: "Lawyer",
        social: "@ella_g",
        certificates: ["Debate Champion"],
        projects: ["School Magazine"]
    },
    {
        id: 4,
        name: "Miguel Tan",
        nickname: "Migs",
        gender: "boy",
        section: "A",
        bio: "Science lover, aspiring doctor. Case study: Bio Research.",
        skills: ["Biology", "Chemistry"],
        hobbies: ["Volleyball", "Painting"],
        favSubject: "Chemistry",
        dreamCareer: "Pediatrician",
        social: "@migs_t",
        certificates: ["Science Fair"],
        projects: ["Bio Research"]
    },
    {
        id: 5,
        name: "Sofia Ramirez",
        nickname: "Sofi",
        gender: "girl",
        section: "B",
        bio: "Tech-savvy, loves design. Case study: Portfolio design system.",
        skills: ["UI/UX", "HTML/CSS"],
        hobbies: ["Photography", "Travel"],
        favSubject: "Computer",
        dreamCareer: "Product Designer",
        social: "@sofi_design",
        certificates: ["Web Design"],
        projects: ["Portfolio"]
    },
    {
        id: 6,
        name: "Andres Rivera",
        nickname: "Dre",
        gender: "boy",
        section: "A",
        bio: "Future architect, loves drawing. Case study: Sustainable House.",
        skills: ["AutoCAD", "Sketching"],
        hobbies: ["Biking", "Modeling"],
        favSubject: "Math",
        dreamCareer: "Architect",
        social: "@dre_arch",
        certificates: ["Drafting"],
        projects: ["Sustainable House"]
    },
    {
        id: 7,
        name: "Isabella Cruz",
        nickname: "Bella",
        gender: "girl",
        section: "A",
        bio: "Dancer and entrepreneur. Case study: E-commerce platform.",
        skills: ["Marketing", "Dance"],
        hobbies: ["Dance", "Fashion"],
        favSubject: "Business",
        dreamCareer: "Entrepreneur",
        social: "@bella_c",
        certificates: ["Business Plan"],
        projects: ["E-commerce"]
    },
    {
        id: 8,
        name: "Lucas Fernandez",
        nickname: "Luke",
        gender: "boy",
        section: "B",
        bio: "Gamer and coder. Case study: Indie Game development.",
        skills: ["C++", "Game Dev"],
        hobbies: ["Gaming", "Music"],
        favSubject: "Computer",
        dreamCareer: "Game Developer",
        social: "@luke_dev",
        certificates: ["Game Jam"],
        projects: ["Indie Game"]
    }
];
