// ============================================================
// STUDENT DATA — GRADE 11-A
// ============================================================
const students = [{
    id: 1,
    name: "Muhammad Ilyas",
    nickname: "Me",
    gender: "Men",
    bio: "The one who knows everything about tech and coding. Future full-stack developer.",
    skills: ["JavaScript", "Python", "React", "UI/UX"],
    hobbies: ["Coding", "Gaming", "Reading"],
    favSubject: "Computer Science",
    dreamCareer: "Full Stack Developer",
    social: "@ilyas_dev",
    certificates: ["Web Development", "Python Programming"],
    projects: ["Class Portfolio", "E-commerce Site"]
}, {
    id: 2,
    name: "Muhammad Nasir",
    nickname: "Garre",
    gender: "Men",
    bio: "Creative editor who brings ideas to life through video and photo editing.",
    skills: ["Video Editing", "Photoshop", "Premiere Pro", "After Effects"],
    hobbies: ["Editing", "Photography", "Watching Movies"],
    favSubject: "Media Studies",
    dreamCareer: "Video Editor / Content Creator",
    social: "@garre_editor",
    certificates: ["Video Editing", "Graphic Design"],
    projects: ["Class Video", "School Documentary"]
}, {
    id: 3,
    name: "Khalid Nasir",
    nickname: "50kilo",
    gender: "Men",
    bio: "Professional gamer with competitive experience in multiple titles.",
    skills: ["Gaming", "Strategy", "Team Coordination", "Streaming"],
    hobbies: ["Gaming", "Streaming", "Watching Esports"],
    favSubject: "Physical Education",
    dreamCareer: "Esports Player / Streamer",
    social: "@50kilo_gamer",
    certificates: ["Esports Tournament", "Game Strategy"],
    projects: ["Gaming Channel", "Tournament Highlights"]
}, {
    id: 4,
    name: "Musab Ali",
    nickname: "Laloo / Lalisa",
    gender: "Men",
    bio: "Quiet but talented. Always ready to help and learn new things.",
    skills: ["Problem Solving", "Teamwork", "Adaptability"],
    hobbies: ["Reading", "Sports", "Helping Others"],
    favSubject: "Mathematics",
    dreamCareer: "Engineer",
    social: "@laloo_musab",
    certificates: ["Math Competition", "Leadership"],
    projects: ["Community Service", "Group Projects"]
}, {
    id: 5,
    name: "Alasad Hussein",
    nickname: "Alo",
    gender: "Men",
    bio: "TikTok influencer and gamer with a growing fanbase. Entertainer at heart.",
    skills: ["Content Creation", "TikTok", "Gaming", "Social Media"],
    hobbies: ["TikTok", "Gaming", "Vlogging", "Dancing"],
    favSubject: "English",
    dreamCareer: "Social Media Influencer",
    social: "@alo_tiktok",
    certificates: ["Content Creation", "Social Media Marketing"],
    projects: ["TikTok Channel", "Gaming Content"]
}, {
    id: 6,
    name: "Abdi Amante",
    nickname: "Crazy",
    gender: "Men",
    bio: "The driver of the group. Always ready to take everyone wherever they need to go.",
    skills: ["Driving", "Navigation", "Car Maintenance", "Responsibility"],
    hobbies: ["Driving", "Cars", "Music", "Travelling"],
    favSubject: "Automotive",
    dreamCareer: "Professional Driver / Mechanic",
    social: "@crazy_abdi",
    certificates: ["Driving License", "Car Maintenance"],
    projects: ["Road Trip Planner", "Car Care Guide"]
}, {
    id: 7,
    name: "Robera Wandimageng",
    nickname: "Robe",
    gender: "Men",
    bio: "The intellectual one. Deep thinker with a passion for knowledge and wisdom.",
    skills: ["Critical Thinking", "Research", "Writing", "Public Speaking"],
    hobbies: ["Reading", "Writing", "Debating", "Philosophy"],
    favSubject: "History",
    dreamCareer: "Academic / Researcher",
    social: "@robera_w",
    certificates: ["Research", "Public Speaking"],
    projects: ["Research Papers", "Debate Club"]
}, {
    id: 8,
    name: "Ra Jahn Dinqa",
    nickname: "Amalakenga",
    gender: "Men",
    bio: "Rap artist with flow and style. Using words to tell stories and inspire.",
    skills: ["Rap", "Songwriting", "Poetry", "Performance"],
    hobbies: ["Rapping", "Writing Lyrics", "Music", "Performing"],
    favSubject: "English",
    dreamCareer: "Rap Artist / Musician",
    social: "@amalakenga_rap",
    certificates: ["Poetry Slam", "Performance Art"],
    projects: ["Mixtape", "Music Videos"]
}];
